FROM nixorg/nix:latest as nix

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update
RUN nix-env -iA \
		nodejs_latest \
		docker \
	-f '<nixpkgs>'

# GitHub Act(or) - local - patch
RUN ln -s /bin/tail /usr/bin/tail
ENV USER=root
