steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=${_DOCKERNAME} --password=$$DOCKERHUB']
  secretEnv: ['DOCKERHUB']

#######################
# NodeJS              #
#######################

# LTS
# Use the image to build the Nix build script.
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
# docker-load the built image.
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs']
# LTS with NPM
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', '--argstr', 'withNPM', 'true', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs-npm']

# LTS @ next
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', '--argstr', 'ver', '${_LTSNEXT}', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'sotekton/containizen:nodejs${_LTSNEXT}', 'sotekton/containizen:nodejs-next']
  id: 'tag-next'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs${_LTSNEXT}']
  waitFor: ['tag-next']
  id: 'push-nodejs${_LTSNEXT}'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs-next']
  waitFor: ['tag-next']
  id: 'push-nodejs-next'
# LTS @ next with NPM
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', '--argstr', 'withNPM', 'true', '--argstr', 'ver', '${_LTSNEXT}', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'sotekton/containizen:nodejs${_LTSNEXT}-npm', 'sotekton/containizen:nodejs-next-npm']
  id: 'tag-next-npm'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs${_LTSNEXT}-npm']
  waitFor: ['tag-next-npm']
  id: 'push-nodejs${_LTSNEXT}-npm'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:nodejs-next-npm']
  waitFor: ['tag-next-npm']
  id: 'push-nodejs-next-npm'

substitutions:
  _DOCKERNAME: sotekton
  _LTSNEXT: '12'
secrets:
  - kmsKeyName: projects/sotekton/locations/global/keyRings/containers/cryptoKeys/dockerhub
    secretEnv:
      DOCKERHUB: CiQApIWz93qWxiCfGBp3LPigGZ9PebTaukp4ZwsJN0S8ShMW7ZMSQgAeTE5Jp4Z6SpdttiD+zAuUCzHzZNhHUybbgh+VkCj8K4rrMsYc3QCwlLO2xirx0ZGbycNiOqUxkeHDS0RZRaBm9Q==

