steps:
# Build the nix-build builder image.
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nix-build', '.']
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=${_DOCKERNAME} --password=$$DOCKERHUB']
  secretEnv: ['DOCKERHUB']

#######################
# NodeJS              #
#######################

# LTS
# Use the image to build the Nix build cript.
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
# docker-load the built image.
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs']
# LTS with NPM
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', '--argstr', 'withNPM', 'true', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs-npm']

# LTS currently v8
# NodeJS 10
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', '--argstr', 'ver', '10', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs10']
# NodeJS 10 with NPM
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', '--argstr', 'withNPM', 'true', '--argstr', 'ver', '10', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs10-npm']

# NodeJS 11
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', '--argstr', 'ver', '11', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs11']
# NodeJS 11 with NPM
- name: gcr.io/$PROJECT_ID/nix-build
  args: ['--cores', '0', '--argstr', 'withNPM', 'true', '--argstr', 'ver', '11', 'languages/node.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/basal:nodejs11-npm']

substitutions:
  _DOCKERNAME: sotekton
secrets:
  - kmsKeyName: projects/sotekton/locations/global/keyRings/containers/cryptoKeys/dockerhub
    secretEnv:
      DOCKERHUB: CiQApIWz93qWxiCfGBp3LPigGZ9PebTaukp4ZwsJN0S8ShMW7ZMSQgAeTE5Jp4Z6SpdttiD+zAuUCzHzZNhHUybbgh+VkCj8K4rrMsYc3QCwlLO2xirx0ZGbycNiOqUxkeHDS0RZRaBm9Q==

