steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=${_DOCKERNAME} --password=$$DOCKERHUB']
  secretEnv: ['DOCKERHUB']

#######################
# Python              #
#######################

# Python 2
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', '--argstr', 'ver', '2', 'languages/python.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:python2']

# Python 3
- name: sotekton/containizen:makisu
  entrypoint: nix-build
  args: ['--cores', '0', '--argstr', 'ver', '3', 'languages/python.nix']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'sotekton/containizen:python3']

substitutions:
  _DOCKERNAME: sotekton
secrets:
  - kmsKeyName: projects/sotekton/locations/global/keyRings/containers/cryptoKeys/dockerhub
    secretEnv:
      DOCKERHUB: CiQApIWz93qWxiCfGBp3LPigGZ9PebTaukp4ZwsJN0S8ShMW7ZMSQgAeTE5Jp4Z6SpdttiD+zAuUCzHzZNhHUybbgh+VkCj8K4rrMsYc3QCwlLO2xirx0ZGbycNiOqUxkeHDS0RZRaBm9Q==

