name: rebuild containizen
on:
  check_suite:
    types: [ 'completed' ]
  push:
    branches:
      - master
  schedule:
    - cron: '15 2 * * *'

jobs:
  makisu:
    name: NixOS & Makisu
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: docker build -t foggyubiquity/containizen:makisu .
      - run: docker push foggyubiquity/containizen:makisu
  nodejs:
    name: NodeJS
    runs-on: ubuntu-latest
    container:
      image: docker://foggyubiquity/containizen:makisu
      volumes:
        - nix:/nix
    strategy:
      matrix:
        version: [10, 12]
        include:
          - version: 12
            next: -next
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: nix-build --cores 0 --argstr ver ${{ matrix.version }} --argstr vulnix true languages/node.nix
      - run: nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -p vulnix --run 'vulnix --whitelist ./vulnix/build.whitelist ./result > vulnerabilities.txt' | true
      - run: nix-build --cores 0 --argstr ver ${{ matrix.version }} languages/node.nix && cp result containizen.tar.gz
      - uses: actions-hub/docker@master
        with:
          args: load -i containizen.tar.gz
      - uses: actions-hub/docker@master
        with:
          args: tag foggyubiquity/containizen:nodejs${{ matrix.version }} foggyubiquity/containizen:nodejs${{ matrix.next }}
      - uses: actions-hub/docker@master
        with:
          args: push foggyubiquity/containizen:nodejs${{ matrix.next }}
      - uses: actions/upload-artifact@v1
        with:
          name: nodejs${{ matrix.next }}.txt
          path: vulnerabilities.txt
  python:
    name: Python
    runs-on: ubuntu-latest
    container:
      image: docker://foggyubiquity/containizen:makisu
      volumes:
        - nix:/nix
    strategy:
      matrix:
        version: [2, 3]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: nix-build --cores 0 --argstr ver ${{ matrix.version }} --argstr vulnix true languages/python.nix
      - run: nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -p vulnix --run 'vulnix --whitelist ./vulnix/build.whitelist ./result > vulnerabilities.txt' | true
      - run: nix-build --cores 0 --argstr ver ${{ matrix.version }} languages/python.nix && cp result containizen.tar.gz
      - uses: actions-hub/docker@master
        with:
          args: load -i containizen.tar.gz
      - uses: actions-hub/docker@master
        with:
          args: push foggyubiquity/containizen:python${{ matrix.version }}
      - uses: actions/upload-artifact@v1
        with:
          name: python${{ matrix.version }}.txt
          path: vulnerabilities.txt

