name: master
on:
  # check_suite:
  #   types: [ 'completed' ]
  push:
    branches:
      - master
  schedule:
    - cron: '15 2 * * *'

jobs:
  makisu:
    name: nixMakisu
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        if: github.actor != 'nektos/act'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: docker build -t foggyubiquity/containizen:makisu .
      - run: docker push foggyubiquity/containizen:makisu
        if: github.actor != 'nektos/act'

  changes:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      nodejs: ${{ steps.filter.outputs.nodejs }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            java:
              - 'languages/java/**'
            nodejs:
              - 'languages/nodejs/**'
            python:
              - 'languages/python/**'

  OCI-java:
    needs: [ changes ]
    if: needs.changes.outputs.java == 'true' && github.event.schedule != '15 2 * * *'
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "java" ]'
      version: '[ 8, 11 ]'
      pkgManager: '[ "none" ]'
      include: '[{"rolling": true, "version": 11}]'
    secrets: inherit

  OCI-nodejs:
    needs: [ changes ]
    if: needs.changes.outputs.nodejs == 'true' && github.event.schedule != '15 2 * * *'
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "nodejs" ]'
      version: '[ 10, 12 ]'
      pkgManager: '[ "none", "bundled" ]'
      include: '[{"rolling": true, "version": 10}, {"language": "nodejs", "pkgManager": "bundled", "pkgManagerName": "-npm"}]'
    secrets: inherit

  OCI-python:
    needs: [ changes ]
    if: needs.changes.outputs.python == 'true' && github.event.schedule != '15 2 * * *'
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "python" ]'
      version: '[ 38 ]'
      pkgManager: '[ "none" ]'
      include: '[{"rolling": true, "version": 38}]'
    secrets: inherit

