name: master
on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      nodejs: ${{ steps.filter.outputs.nodejs }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - name: DockerHub login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            java:
              - 'languages/java/**'
            nodejs:
              - 'languages/nodejs/**'
            python:
              - 'languages/python/**'

  OCI-java:
    needs: [ changes ]
    # .github/workflows won't pass as an output from 'changes' adding negative
    # condition to ensure runs of config file changes on 'push'
    if: >-
      ${{
        needs.changes.outputs.nodejs == 'true' ||
        (
          needs.changes.outputs.java != 'true' &&
          needs.changes.outputs.nodejs != 'true' &&
          needs.changes.outputs.python != 'true'
        )
      }}
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "java" ]'
      version: '[ 8, 11 ]'
      pkgManager: '[ "none" ]'
      include: '[{"rolling": true, "version": 11}]'
    secrets: inherit

  OCI-nodejs:
    needs: [ changes ]
    if: >-
      ${{
        needs.changes.outputs.nodejs == 'true' ||
        (
          needs.changes.outputs.java != 'true' &&
          needs.changes.outputs.nodejs != 'true' &&
          needs.changes.outputs.python != 'true'
        )
      }}
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "nodejs" ]'
      version: '[ 14, 16, 18 ]'
      pkgManager: '[ "none", "bundled" ]'
      # Leaving in as quick-note on adding -npm should it be desired by others
      # include: '[{"rolling": true, "version": 18}, {"language": "nodejs", "pkgManager": "bundled", "pkgManagerName": "-npm"}]'
      include: '[{"rolling": true, "version": 18}]'
    secrets: inherit

  OCI-python:
    needs: [ changes ]
    if: >-
      ${{
        needs.changes.outputs.python == 'true' ||
        (
          needs.changes.outputs.java != 'true' &&
          needs.changes.outputs.nodejs != 'true' &&
          needs.changes.outputs.python != 'true'
        )
      }}
    uses: ./.github/workflows/common-oci.yaml
    with:
      language: '[ "python" ]'
      version: '[ 38, 39, 310, 311, 312 ]'
      pkgManager: '[ "none" ]'
      include: '[{"rolling": true, "version": 312}]'
    secrets: inherit

